<a href="https://colab.research.google.com/github/1998456/1998456/blob/main/Matrix(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Dependencies:

In [ ]:
import numpy as np

MATRIX ADDITION

In [ ]:
# Addition will only be possible if both matrix have similar shape:
a= np.asarray([[2,3],[3,4]])

b= np.asarray([[4,5],[7,8]])

In [ ]:
print(a)

[[2 3]
 [3 4]]


In [ ]:
print(b)

[[4 5]
 [7 8]]


In [ ]:
sum= a+b

In [ ]:
sum

array([[ 6,  8],
       [10, 12]])

In [ ]:
# Using Random Value Functions:
b= np. random. randint(10,size=(3,3))

c= np. random. randint(10,size=(3,3))

In [ ]:
print(b)

[[3 5 8]
 [3 6 6]
 [3 3 6]]


In [ ]:
print(c)

[[9 4 3]
 [2 3 4]
 [6 2 0]]


In [ ]:
sum= np.add(b,c)

In [ ]:
sum

array([[12,  9, 11],
       [ 5,  9, 10],
       [ 9,  5,  6]])