<a href="https://colab.research.google.com/github/1998456/1998456/blob/main/Matrix(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Dependencies:

In [3]:
import numpy as np

MATRIX ADDITION

In [ ]:
# Addition will only be possible if both matrix have similar shape:
a= np.asarray([[2,3],[3,4]])

b= np.asarray([[4,5],[7,8]])

In [ ]:
print(a)

[[2 3]
 [3 4]]


In [ ]:
print(b)

[[4 5]
 [7 8]]


In [ ]:
sum= a+b

In [ ]:
sum

array([[ 6,  8],
       [10, 12]])

In [ ]:
# Using Random Value Functions:
b= np. random. randint(10,size=(3,3))

c= np. random. randint(10,size=(3,3))

In [ ]:
print(b)

[[3 5 8]
 [3 6 6]
 [3 3 6]]


In [ ]:
print(c)

[[9 4 3]
 [2 3 4]
 [6 2 0]]


In [ ]:
sum= np.add(b,c)

In [ ]:
sum

array([[12,  9, 11],
       [ 5,  9, 10],
       [ 9,  5,  6]])

Adding Matrixes Of different Shape;

In [12]:
m2= np.random.randint(10,size=(3,3))
m3= np.random.randint(12,size=(3,3))

In [13]:
sum= np.add(m2,m3)

In [14]:
sum

array([[ 0, 16,  9],
       [10, 18,  4],
       [ 6,  3,  8]])

In [20]:
m2= np.random.randint(10,size=(3,3))
m3= np.random.randint(12,size=(5,3))

In [25]:
sum2= np.add(m2,m3)

ValueError: operands could not be broadcast together with shapes (3,3) (5,3) 

In [26]:
sum2

NameError: name 'sum2' is not defined

Matrix Subtraction :

In [29]:
a= np.array([[2,3],[4,5]])

b= np.array([[6,7],[8,9]])

In [31]:
print(a)

[[2 3]
 [4 5]]


In [32]:
print(b)

[[6 7]
 [8 9]]


In [33]:
subt=a-b

In [34]:
print(subt)

[[-4 -4]
 [-4 -4]]


Random Matrix Subtraction :

In [35]:

# Subtracting Matrix of similar shape:
m4= np.random.randint(10,size=(3,3))
m5= np.random.randint(10,size=(3,3))

In [37]:
subt= np.subtract(m4,m5)

In [38]:
subt

array([[-2, -7,  9],
       [ 3,  7,  3],
       [ 8, -3,  2]])

In [39]:
# Subtracting Matrix of Different Shape:
m4= np.random.randint(10,size=(3,3))
m5= np.random.randint(12,size=(3,3))

In [40]:
subt= np.subtract(m4,m5)

In [41]:
print(subt)

[[ 1 -3  6]
 [-6  7  1]
 [ 8 -3 -7]]


In [42]:
# Subtracting Matrix Of Different Shape:
m4= np.random.randint(10,size=(3,3))
m5= np.random.randint(10,size=(4,3))

In [45]:
subt2= np.subtract(m4,m5)

ValueError: operands could not be broadcast together with shapes (3,3) (4,3) 

In [46]:
print(subt2)

NameError: name 'subt2' is not defined

Matrix Multiplication:

In [49]:
# Multiplying with a Scalar:
x=5
y= np.random.randint(10,size=(4,4))

In [51]:
product= np.multiply(x,y)
product

array([[40, 40, 25, 20],
       [10, 25, 15,  5],
       [10, 10,  5, 40],
       [15, 20, 30,  0]])

In [57]:
# Multiplying 2 Matrixes of Similar Shape:
m5= np.random.randint(10,size=(3,3))

m6= np.random.randint(10,size=(3,3))

In [58]:
print(m5)

[[2 4 2]
 [1 4 4]
 [7 9 5]]


In [59]:
print(m6)

[[6 0 8]
 [4 9 2]
 [1 8 9]]


In [61]:
product= np.dot(m5,m6)
product

array([[ 30,  52,  42],
       [ 26,  68,  52],
       [ 83, 121, 119]])

In [80]:
# Multiplying 2 Matrixes of different shape:
m6= np.random.randint(10,size=(3,3))

m7= np.random.randint(12,size=(4,4))

In [81]:
print(m6)

[[1 0 0]
 [6 3 7]
 [6 7 6]]


In [82]:
print(m7)

[[1 2 5 3]
 [5 4 3 2]
 [4 5 0 0]
 [5 8 3 7]]


In [83]:
product= np.dot(m6,m7)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

In [84]:
product

array([[ 10,   2,   7],
       [146,  62,  55],
       [ 86,  50,  13]])