<a href="https://colab.research.google.com/github/1998456/1998456/blob/main/MOD(MATRIX_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Creating Matrix Using Numpy;

In [6]:
m1= np.array([[2,3],[6,7]])
print(m1)

[[2 3]
 [6 7]]


Working With 2 Dimensions;


In [7]:
m1.shape

(2, 2)

Working With 3 Dimensions;

In [14]:
m2= np.array([[2,3],[3,4],[6,7]])
print(m2)

[[2 3]
 [3 4]
 [6 7]]


In [15]:
m2.shape

(3, 2)

Creating Matrix With Random Values;

In [17]:
rndmatrix=np.random.rand(3,2)
print(rndmatrix)

[[0.08874797 0.59286783]
 [0.13708321 0.93362025]
 [0.66125722 0.92086314]]


Creating Matrix With Random Integers;

In [19]:
rndintegers=np.random.randint(100,size=(4,5))
print(rndintegers)

[[72 37 41 74 76]
 [88 87 58 34 73]
 [ 4 82 73 86 28]
 [99 60 96 90 23]]


Matrix With All Values As 1;

In [24]:
m3=np.ones((2,3))
print(m3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
m3=np.ones((2,3),dtype=int)
print(m3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
m3=np.ones((10,10),dtype=int)
print(m3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Creating Null / Zero Matrix

In [32]:
nullmatrix=np.zeros((4,4))
print(nullmatrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
nullmatrix=np.zeros((7,7))
print(nullmatrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [35]:
identity_matrix= np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
identity_matrix= np.eye(6,6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Transpose Of Matrix

In [42]:
a= np.random.randint(100,size=(4,5))
print(a)

[[84 81 48 77  9]
 [33 35 54 58 49]
 [23 91 97 64 46]
 [96 27 79 29 13]]


In [44]:
transpose_of_a= np.transpose(a)
print(transpose_of_a)

[[84 33 23 96]
 [81 35 91 27]
 [48 54 97 79]
 [77 58 64 29]
 [ 9 49 46 13]]
